version: "3.7"
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - mysql
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/server_db
  #     SPRING_DATASOURCE_USERNAME: server
  #     SPRING_DATASOURCE_PASSWORD: server
  #   restart: on-failure

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server_db
      MYSQL_USER: server
      MYSQL_PASSWORD: server
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
